[logger]
level = "INFO"
path = "stdout"

[database]
db_type = "postgres"
conn_str = "postgresql://localhost/calendar?user=postgres&password=sqlSync24&sslmode=disable"
max_conns = 20

[rabbit]
url = "amqp://guest:guest@localhost:5672/"

[app]
check_interval = "2s"
remove_after = "1y"
