version: "3"

services:

  calendar:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_calendar
    command: /opt/calendar/calendar-app -config /etc/calendar/config.toml
    ports:
      # - 4242:4242
      - 4343:4343
    network_mode: host

#   calendar:
#     restart: always
#     build:
#       context: ./
#       dockerfile: Dockerfile-calendar
#     depends_on:
#       - rabbitmq
#       - db
#     ports:
#       - 4444:4444
#       - 4445:4445
#       - 4446:4446
#     environment:
#       DSN: ${DSN}
#       RABBIT_ADDR: ${RABBIT_ADDR}

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    network_mode: host
    depends_on:
      - calendar